apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rs
  namespace: test
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test-rs
  template:
    metadata:
      labels:
        app: test-rs
        "compId" : "test-TOPO"
        "isJava" : "yes"
    spec:
      containers:
      - name: test-rs
        env:
        xxxx
        image: xxxx
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 4000Mi
        volumeMounts:
        - mountPath: /opt/test/log
          name: locallog
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /opt/test/config/resources/images
          name: testimgdir
        livenessProbe:
          httpGet:
            path: /lives/hello
            port: 8091
          initialDelaySeconds: 600
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: locallog
        hostPath:
          path: /var/lib/ssdata/xxx/xxx/test-rs
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: testimgdir
        persistentVolumeClaim:
          claimName: test-gluster-pvc
