apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-gluster-pv
  labels:
    pv: test-gluster-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gfs-storage-testimages
    path: testimages
