apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-gluster-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: test-gluster-pv
